development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
<<<<<<< HEAD
  channel_prefix: ruby_on_rails_practise_app_production
=======
  channel_prefix: rails_project_production
>>>>>>> 1df4e09 (configured bootstrap and built skeleton home page)
